### ISSUE TITLE
Add more verbosity to matter-labs test output

### ISSUE THREAD

**Issue by IkerAlus** [bee344/evm-tests#18]
At the moment, if the test passes, the output of the matter labs test is something like:

```
  Matter Labs EVM Tests
    ✔ Run Test Suite (24162ms)


  1 passing (24s)
```
As a suggestion, it would be nice to be able to add more data points to this output. For example,  showing each test category, with the time used and if it passed or not.  

Also, it would be good to add the possibility of logging the test results in a file.

**Comment by bee344** [comment]
The logging is covered in #13 . Now the logs are written to a JSON file.
